annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Docker Compose based installer for Docker Desktop extension
    - kind: changed
      description: Docker Image size optimization for faster installation
    - kind: added
      description: Gitlab person access token support added
    - kind: changed
      description: EKS cluster create - UX improvements for Master role ARN, Node role ARN & ALB role
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: gopaddle
  catalog.cattle.io/kube-version: '>=1.21-0'
  catalog.cattle.io/namespace: gopaddle
  catalog.cattle.io/release-name: gopaddle
apiVersion: v2
appVersion: 4.2.9
dependencies:
- condition: global.installer.chart.gp-core
  name: gp-core
  repository: file://./charts/gp-core
- condition: global.installer.chart.rabbitmq
  name: gp-rabbitmq
  repository: file://./charts/gp-rabbitmq
description: Simple low-code platform for Kubernetes developers and operators
home: https://gopaddle.io
icon: https://gopaddle-marketing.s3.ap-southeast-2.amazonaws.com/gopaddle.png
keywords:
- low-code
- Internal Developer Platform
- PaaS
- Community Edition
kubeVersion: '>=1.21-0'
name: gopaddle
version: 4.2.9
