activitymanager:
  activitymanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
alertmanager:
  alertmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
appscanner:
  appscanner:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
appworker:
  appworker:
    envMap:
      NODE_NAME: spec.nodeName
      rabbitmq_user: admin
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
cloudmanager:
  cloudmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
clustermanager:
  clustermanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
clustertemplatemanager:
  clustertemplatemanager:
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
configmanager:
  configmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.2
    imageTagArm: multi-arch-4.2.7.lite.2
costmanager:
  costmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
deploymentmanager:
  deploymanager:
    envMap:
      NODE_NAME: spec.nodeName
      rabbitmq_user: admin
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
domainmanager:
  domainmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
esearch:
  esearch:
    envMap:
      discovery.type: single-node
    image: elasticsearch:7.12.0
    imageTag: 1.7.3
    imageTagArm: 7.8.0
gateway:
  gateway:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
  gpkubeux:
    envMap:
      HOST: 0.0.0.0
    imageTag: multi-arch-4.2.7.lite.2
    imageTagArm: multi-arch-4.2.7.lite.2
    gpReleaseVersion: 4.2.9
gpcore:
  core:
    envMap:
      NODE_IP: rabbitmq-build-external.$(NAMESPACE).svc.cluster.local
      NODE_NAME: spec.nodeName
      NODE_PORT: "5672"
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
influxdb:
  influxdb:
    envMap:
      INFLUXDB_ADMIN_PASSWORD: cGFzc3dvcmQ
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    image: influxdb
    imageTag: 1.7.10
mongodb:
  mongo:
    envMap:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_LITE_USERNAME: lite
    image: mongo
    imageTag: 4.0.4
  mongoInit:
    image: mongo
    imageTag: 4.0.4
nodechecker:
  nodechecker:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
paymentmanager:
  paymentmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
rabbitmq:
  rabbitmq:
    envMap:
      RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ
      RABBITMQ_DEFAULT_USER: admin
    image: rabbitmq
    imageTag: 3.8.5
redis:
  redis:
    image: redis
    imageTag: 3.2-alpine
usermanager:
  usermanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.9.lite.1
    imageTagArm: multi-arch-4.2.9.lite.1
webhook:
  webhook:
    envMap:
      APP_NAME: metadata.namespace
      HOST_IP: status.hostIP
      NODE_NAME: spec.nodeName
      REPLICA_IP: status.podIP
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
marketplace:
  marketplace:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: multi-arch-4.2.7.lite.1
    imageTagArm: multi-arch-4.2.7.lite.1
emailer:
  emailer:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.7.lite.17
    imageTagArm: 4.2.7.lite-arm64.1
defaultbackend:
  defaultbackend:
    image: defaultbackend
    imageArm: defaultbackend-arm64
    imageTag: 1.4
nginxIngress:
  nginxIngress:
    image: nginx/nginx-ingress
    imageTag: 3.1-alpine