apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esearch
  namespace: {{ .Release.Namespace }}
  labels:
    app: esearch
    app-id: appsab909ba8cbe61c46e1cb3f9c4dffd24b038a
    family: servicegroup
    name: esearch
    released-by: gopaddle
    servicegroup: esearch-lz5zjizb
    servicegroup-name: esearch
spec:
  serviceName: esearch-headless
  replicas: 1
  selector:
    matchLabels:
      component: esearch
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: esearch
        app-id: appsab909ba8cbe61c46e1cb3f9c4dffd24b038a
        family: servicegroup
        name: esearch
        released-by: gopaddle
        servicegroup: esearch-lz5zjizb
        component: esearch
      name: esearch
    spec:
      affinity: {}
{{- if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - name: esearch
        image: {{ .Values.esearch.esearch.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: cGFzc3dvcmQ
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: data
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            cpu: "1"
            memory: 2G
          requests:
            cpu: 300m
            memory: 500M
      # Allow non-root user to access PersistentVolume
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      volumes:
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app: data
        app-id: appsab909ba8cbe61c46e1cb3f9c4dffd24b038a
        name: esearch
        released-by: gopaddle
        servicegroup: esearch-lz5zjizb
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        limits:
          storage: 20Gi
        requests:
          storage: 10Gi
      storageClassName: {{ template "gopaddle.storageClass" . }}
      volumeMode: Filesystem
    status: {}
